datagrids:
    teachers-assignments-grid:
        extended_entity_name: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment'
        acl_resource: teachers_assignment_view
        source:
            type: orm
            query:
                select:
                    - assignment.id
                    - assignment.subject
                    - assignment.createdAt
                    - CONCAT(course_manager.firstName, course_manager.lastName) as courseManagerFullName
                from:
                    - { table: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment', alias: assignment }
                join:
                    inner:
                        - { join: assignment.courseManager, alias: course_manager }
        columns:
            subject:
                label: teachers.assignment.subject.label
            courseManagerFullName:
                label: teachers.assignment.course_manager_name.label
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
        sorters:
            columns:
                subject:
                    data_name: assignment.subject
                createdAt:
                    data_name: assignment.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                subject:
                    type: string
                    data_name: assignment.subject
                createdAt:
                    type: datetime
                    data_name: assignment.createdAt
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_assignment_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_assignment_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_assignment_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_assignment_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_assignment_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_assignment_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.assignment.entity_plural_label
            entity_pagination: true

    teachers-assignments-teacher-grid:
        extends: teachers-assignments-grid
        source:
            type: orm
            query:
                select:
                    - tg.title as tgtitle
                join:
                    inner:
                        - { join: assignment.teacherGroups, alias: tg }
                        - { join: Teachers\Bundle\UsersBundle\Entity\TeacherGroupToUser, alias: tg_to_usr, conditionType: WITH, condition: "tg_to_usr.teacherGroup = tg.id" }
                        - { join: tg_to_usr.user, alias: tg_user }
                where:
                    and:
                        - tg_user.id = @oro_security.token_accessor->getUserId
        columns:
            tgtitle:
                label: teachers.assignment.teacher_group.label
