datagrids:
    teachers-assignments-grid:
        extended_entity_name: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment'
        acl_resource: teachers_assignment_view
        source:
            type: orm
            query:
                select:
                    - assignment.id
                    - assignment.firstName
                    - assignment.lastName
                    - assignment.courseName
                    - assignment.coursePrefixes
                    - assignment.workToday
                    - assignment.dueDate
                    - assignment.courseUrl
                    - assignment.userLogin
                    - assignmentterm.name as termName
                    - assignmentterm.id as termId
                    - assignment.createdAt
                    - CONCAT(course_manager.firstName, course_manager.lastName) as courseManagerFullName
                from:
                    - { table: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment', alias: assignment }
                join:
                    inner:
                        - { join: assignment.courseManager, alias: course_manager }
                    left:
                        - { join: assignment.term, alias: assignmentterm }
        columns:
            firstName:
                label: teachers.assignment.first_name.label
            lastName:
                label: teachers.assignment.last_name.label
            courseName:
                label: teachers.assignment.course_name.label
            coursePrefixes:
                label: teachers.assignment.course_prefixes.label
            workToday:
                label: teachers.assignment.work_today.label
                frontend_type: select
                choices:
                    teachers.assignment.work_today.true.label: enabled
                    teachers.assignment.work_today.false.label: disabled
            dueDate:
                frontend_type: datetime
                label: teachers.assignment.due_date.label
            courseUrl:
                label: teachers.assignment.course_url.label
            userLogin:
                label: teachers.assignment.user_login.label
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
            termName:
                label: teachers.assignment.term.label
        sorters:
            columns:
                firstName:
                    data_name: assignment.firstName
                lastName:
                    data_name: assignment.lastName
                courseName:
                    data_name: assignment.courseName
                coursePrefixes:
                    data_name: assignment.coursePrefixe
                dueDate:
                    data_name: assignment.dueDate
                courseUrl:
                    data_name: assignment.courseUrl
                userLogin:
                    data_name: assignment.userLogin
                createdAt:
                    data_name: assignment.createdAt
                termName:
                    data_name: termName
            default:
                createdAt: DESC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: assignment.firstName
                lastName:
                    type: string
                    data_name: assignment.lastName
                courseName:
                    type: string
                    data_name: assignment.courseName
                coursePrefixe:
                    type: string
                    data_name: assignment.coursePrefixe
                workToday:
                    data_name: c.enabled
                    type: choice
                    options:
                        field_options:
                            choices:
                                teachers.assignment.work_today.false.label: 0
                                teachers.assignment.work_today.true.label: 1
                dueDate:
                    type: string
                    data_name: assignment.dueDate
                courseUrl:
                    type: string
                    data_name: assignment.courseUrl
                userLogin:
                    type: string
                    data_name: assignment.userLogin
                createdAt:
                    type: datetime
                    data_name: assignment.createdAt
                termName:
                    type: enum
                    enum_code: application_term
                    data_name: termId
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_assignment_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_assignment_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_assignment_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_assignment_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_assignment_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_assignment_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.assignment.entity_plural_label
            entity_pagination: true

    teachers-assignments-teacher-grid:
        extends: teachers-assignments-grid
        source:
            type: orm
            query:
                select:
                    - tg.title as tgtitle
                join:
                    inner:
                        - { join: assignment.teacherGroups, alias: tg }
                        - { join: Teachers\Bundle\UsersBundle\Entity\TeacherGroupToUser, alias: tg_to_usr, conditionType: WITH, condition: "tg_to_usr.teacherGroup = tg.id" }
                        - { join: tg_to_usr.user, alias: tg_user }
                where:
                    and:
                        - tg_user.id = @oro_security.token_accessor->getUserId
        columns:
            tgtitle:
                label: teachers.assignment.teacher_group.label

    teachers-assignments-my-grid:
        extends: teachers-assignments-grid
        source:
            type: orm
            query:
                join:
                    left:
                        - { join: assignment.teacher, alias: asgm_teacher }
                        - { join: assignment.student, alias: asgm_student }
                where:
                    or:
                        - asgm_teacher.id = @oro_security.token_accessor->getUserId
                        - asgm_student.id = @oro_security.token_accessor->getUserId
                        - course_manager.id = @oro_security.token_accessor->getUserId

    teachers-assignment-messages-grid:
        extended_entity_name: 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
        acl_resource: teachers_assignment_message_view
        views_list: "@teachers_assignment.message.datagrid_view_list"
        source:
            type: orm
            query:
                select:
                    - assignment_message.id
                    - assignment_message.message
                    - assignment_message.createdAt
                    - CONCAT(message_sender.firstName, message_sender.lastName) as senderFullName
                    - message_status.id as status
                    - message_status.name as statusLabel
                from:
                    - { table: 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage', alias: assignment_message }
                join:
                    inner:
                        - { join: assignment_message.owner, alias: message_sender }
                        - { join: assignment_message.status, alias: message_status }
        columns:
            message:
                label: teachers.assignment.message.message.label
            senderFullName:
                label: teachers.assignment.message.sender_name.label
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
        sorters:
            columns:
                message:
                    data_name: assignment_message.message
                createdAt:
                    data_name: assignment_message.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                message:
                    type: string
                    data_name: assignment_message.message
                createdAt:
                    type: datetime
                    data_name: assignment_message.createdAt
                statusLabel:
                    label: teachers.assignment.message.status.label
                    type: enum
                    data_name: status
                    enum_code: assignment_msg_status
        properties:
            id: ~
            approve_link:
                type: url
                route: teachers_assignment_message_approve
                params: [ id ]
            unapprove_link:
                type: url
                route: teachers_assignment_message_unapprove
                params: [ id ]
        actions:
            approve:
                acl_resource: teachers_assignment_message_edit
                type: ajaxdelete
                requestType: POST
                label: teachers.assignment.grid.action.approve
                icon: thumbs-up
                link: approve_link
                defaultMessages:
                    confirm_title: teachers.assignment.action.confirm_title.approve
                    confirm_ok: teachers.assignment.action.confirm_ok
                    confirm_cancel: teachers.assignment.action.confirm_cancel
                    confirm_content: teachers.assignment.action.content.approve
                    success: teachers.assignment.action.success.approve
                    error: teachers.assignment.action.error.approve
            unapprove:
                type: dialog
                acl_resource: teachers_assignment_message_edit
                label: teachers.assignment.grid.action.unapprove
                icon: thumbs-down
                link: unapprove_link
                widgetOptions:
                    reload-grid-name: teachers-assignment-messages-grid
                    options:
                        dialogOptions:
                            title: Mark Message as dangerous and left a comment
                            width: 550
                            allowMaximize: false
                            allowMinimize: false
                            modal: true
                            maximizedHeightDecreaseBy: minimize-bar
        options:
            entityHint: teachers.assignment.message.entity_plural_label
            entity_pagination: true
