datagrids:
    teachers-assignments-grid:
        extended_entity_name: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment'
        acl_resource: teachers_assignment_view
        views_list: '@teachers_assignment.assignments.datagrid_view_list'
        source:
            type: orm
            query:
                select:
                    - assignment.id
                    - assignment.firstName
                    - assignment.lastName
                    - assignment.courseName
                    - assignment.coursePrefixes
                    - assignment.workToday
                    - assignment.amountDueToday
                    - assignment.dueDate
                    - assignment.courseUrl
                    - assignment.userLogin
                    - assignmentterm.name as termName
                    - assignmentterm.id as termId
                    - assignment.createdAt
                    - CONCAT_WS(' ', course_manager.firstName, course_manager.lastName) as courseManagerFullName
                    - CONCAT_WS(' ', teacher.firstName, teacher.lastName) as teacherName
                    - CONCAT_WS(' ', student.firstName, student.lastName) as studentName
                from:
                    - { table: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment', alias: assignment }
                join:
                    inner:
                        - { join: assignment.courseManager, alias: course_manager }
                    left:
                        - { join: assignment.term, alias: assignmentterm }
                        - { join: assignment.teacher, alias: teacher }
                        - { join: assignment.student, alias: student }
                        - { join: assignment.courseManager, alias: courseManager }
                groupBy: assignment.id
        columns:
            firstName:
                label: teachers.assignment.first_name.label
                order: 10
            lastName:
                label: teachers.assignment.last_name.label
                order: 20
            courseName:
                label: teachers.assignment.course_name.label
                order: 30
            coursePrefixes:
                label: teachers.assignment.course_prefixes.label
                order: 40
            amountDueToday:
                label: teachers.assignment.amountDueToday.label
                type: twig
                frontend_type: html
                template: TeachersApplicationBundle:Datagrid:price.html.twig
                order: 50
            workToday:
                label: teachers.assignment.work_today.label
                frontend_type: select
                choices:
                    teachers.assignment.work_today.true.label: 1
                    teachers.assignment.work_today.false.label: 0
                order: 60
            dueDate:
                frontend_type: datetime
                label: teachers.assignment.due_date.label
                order: 70
            courseUrl:
                label: teachers.assignment.course_url.label
                order: 80
            userLogin:
                label: teachers.assignment.user_login.label
                order: 90
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
                order: 100
            termName:
                label: teachers.assignment.term.label
                order: 110
            teacherName:
                label: teachers.assignment.teacher.label
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/related-id-relation-editor-view
                        view_options:
                            value_field_name: teacher
                    autocomplete_api_accessor:
                        search_handler_name: users_only_teachers
                        label_field_name: fullName
                        class: orouser/js/tools/acl-users-search-api-accessor
                        permission_check_entity_name: Teachers_Bundle_AssignmentBundle_Entity_Assignment
                order: 120
        sorters:
            columns:
                firstName:
                    data_name: assignment.firstName
                lastName:
                    data_name: assignment.lastName
                courseName:
                    data_name: assignment.courseName
                coursePrefixes:
                    data_name: assignment.coursePrefixe
                amountDueToday:
                    data_name: application.amountDueToday
                dueDate:
                    data_name: assignment.dueDate
                courseUrl:
                    data_name: assignment.courseUrl
                userLogin:
                    data_name: assignment.userLogin
                createdAt:
                    data_name: assignment.createdAt
                termName:
                    data_name: termName
                teacherName:
                    data_name: teacherName
            default:
                createdAt: DESC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: assignment.firstName
                lastName:
                    type: string
                    data_name: assignment.lastName
                courseName:
                    type: string
                    data_name: assignment.courseName
                coursePrefixes:
                    type: string
                    data_name: assignment.coursePrefixes
                amountDueToday:
                    type: string
                    data_name: application.amountDueToday
                workToday:
                    data_name: c.enabled
                    type: choice
                    options:
                        field_options:
                            choices:
                                teachers.assignment.work_today.false.label: 0
                                teachers.assignment.work_today.true.label: 1
                dueDate:
                    type: string
                    data_name: assignment.dueDate
                courseUrl:
                    type: string
                    data_name: assignment.courseUrl
                userLogin:
                    type: string
                    data_name: assignment.userLogin
                createdAt:
                    type: datetime
                    data_name: assignment.createdAt
                termName:
                    type: enum
                    enum_code: application_term
                    data_name: termId
                teacherName:
                    type: choice-tree
                    label: teachers.assignment.teacher.label
                    data_name: assignment.teacher
                    autocomplete_alias: users_only_teachers
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_assignment_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_assignment_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_assignment_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_assignment_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_assignment_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_assignment_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.assignment.entity_plural_label
            entity_pagination: true

    user-assignments-grid:
        extends: teachers-assignments-grid
        source:
            query:
                where:
                    and:
                        - (teacher.id = :id OR student.id = :id OR courseManager.id = :id)
            bind_parameters:
                - id
        options:
            entity_pagination: false

    teachers-assignments-teacher-grid:
        extends: teachers-assignments-grid
        source:
            type: orm
            query:
                select:
                    - GROUP_CONCAT(tg.title) as tgtitle
                join:
                    inner:
                        - { join: assignment.teacherGroups, alias: tg }
                        - { join: Teachers\Bundle\UsersBundle\Entity\TeacherGroupToUser, alias: tg_to_usr, conditionType: WITH, condition: "tg_to_usr.teacherGroup = tg.id" }
                        - { join: tg_to_usr.user, alias: tg_user }
                        - { join: assignment.status, alias: status }
                where:
                    and:
                        - tg_user.id = @oro_security.token_accessor->getUserId
                        - status.id = 'up_for_bid'
                groupBy: assignment.id
        columns:
            tgtitle:
                label: teachers.assignment.teacher_group.label

    teachers-assignments-my-grid:
        extends: teachers-assignments-grid
        source:
            type: orm
            query:
                join:
                    left:
                        - { join: assignment.teacher, alias: asgm_teacher }
                        - { join: assignment.student, alias: asgm_student }
                where:
                    or:
                        - asgm_teacher.id = @oro_security.token_accessor->getUserId
                        - asgm_student.id = @oro_security.token_accessor->getUserId
                        - course_manager.id = @oro_security.token_accessor->getUserId

    teachers-assignment-messages-grid:
        extended_entity_name: 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
        acl_resource: teachers_assignment_message_view
        views_list: "@teachers_assignment.message.datagrid_view_list"
        source:
            type: orm
            query:
                select:
                    - assignment_message.id
                    - assignment_message.message
                    - assignment_message.createdAt
                    - CONCAT(message_sender.firstName, message_sender.lastName) as senderFullName
                    - message_status.id as status
                    - message_status.name as statusLabel
                from:
                    - { table: 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage', alias: assignment_message }
                join:
                    inner:
                        - { join: assignment_message.owner, alias: message_sender }
                        - { join: assignment_message.status, alias: message_status }
        columns:
            message:
                label: teachers.assignment.message.message.label
                type: twig
                frontend_type: html
                template: TeachersAssignmentBundle:AssignmentMessage/Datagrid:message.html.twig
            senderFullName:
                label: teachers.assignment.message.sender_name.label
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
        sorters:
            columns:
                message:
                    data_name: assignment_message.message
                createdAt:
                    data_name: assignment_message.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                message:
                    type: string
                    data_name: assignment_message.message
                createdAt:
                    type: datetime
                    data_name: assignment_message.createdAt
                statusLabel:
                    label: teachers.assignment.message.status.label
                    type: enum
                    data_name: status
                    enum_code: assignment_msg_status
        properties:
            id: ~
            approve_link:
                type: url
                route: teachers_assignment_message_approve
                params: [ id ]
            unapprove_link:
                type: url
                route: teachers_assignment_message_unapprove
                params: [ id ]
        actions:
            approve:
                acl_resource: teachers_assignment_message_edit
                type: ajaxdelete
                requestType: POST
                label: teachers.assignment.grid.action.approve
                icon: thumbs-up
                link: approve_link
                defaultMessages:
                    confirm_title: teachers.assignment.action.confirm_title.approve
                    confirm_ok: teachers.assignment.action.confirm_ok
                    confirm_cancel: teachers.assignment.action.confirm_cancel
                    confirm_content: teachers.assignment.action.content.approve
                    success: teachers.assignment.action.success.approve
                    error: teachers.assignment.action.error.approve
            unapprove:
                type: dialog
                acl_resource: teachers_assignment_message_edit
                label: teachers.assignment.grid.action.unapprove
                icon: thumbs-down
                link: unapprove_link
                widgetOptions:
                    reload-grid-name: teachers-assignment-messages-grid
                    options:
                        dialogOptions:
                            title: Mark Message as dangerous and left a comment
                            width: 550
                            allowMaximize: false
                            allowMinimize: false
                            modal: true
                            maximizedHeightDecreaseBy: minimize-bar
        options:
            entityHint: teachers.assignment.message.entity_plural_label
            entity_pagination: true
