navigation:
    menu_config:
        items:
            teachers_assignment_assignment:
                label: 'teachers.assignment.entity_plural_label'
                route: 'teachers_assignment_index'
                position: 12
                extras:
                    routes: [ 'teachers_assignment_*' ]
                    icon: fa-paperclip
                display: true
            teachers_assignment_assignment_teacher:
                label: 'teachers.assignment.teachers_queue_label'
                route: 'teachers_assignment_teacher_index'
                position: 12
                extras:
                    routes: [ 'teachers_assignment_*' ]
                    icon: fa-paperclip
                display: true
            teachers_assignment_assignment_my:
                label: 'teachers.assignment.my_courses_label'
                route: 'teachers_assignment_my_courses'
                position: 12
                extras:
                    routes: [ 'teachers_assignment_*' ]
                    icon: fa-paperclip
                display: true
            teachers_assignment_assignment_messages:
                label: 'teachers.assignment.approval_queue_label'
                position: 13
                route: 'teachers_assignment_message_index'
                extras:
                    routes: [ 'teachers_assignment_message_*' ]
                    icon: fa-envelope
                display: true
        tree:
            application_menu:
                children:
                    teachers_assignment_assignment: ~
                    teachers_assignment_assignment_teacher: ~
                    teachers_assignment_assignment_my: ~
                    teachers_assignment_assignment_messages: ~
    titles:
        teachers_assignment_index: ~
        teachers_assignment_view: '%assignment.subject%'
        teachers_assignment_create: 'Create assignment'
        teachers_assignment_update: '%assignment.subject% - Edit'
