oro_permissions:
    VIEW_TEACHERS_QUEUE:
        label: teachers.assignment.permission.view_teachers_queue.label
        group_names: ""
        apply_to_all: false
        apply_to_entities:
            - 'Teachers\Bundle\AssignmentBundle\Entity\Assignment'
    VIEW_MY_COURSES:
        label: teachers.assignment.permission.view_my_courses.label
        group_names: ""
        apply_to_all: false
        apply_to_entities:
            - 'Teachers\Bundle\AssignmentBundle\Entity\Assignment'
    VIEW_MESSAGES_APPROVAL_QUEUE:
        label: teachers.assignment.permission.view_messages_approval_queue.label
        group_names: ""
        apply_to_all: false
        apply_to_entities:
            - 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
    VIEW_MY_MESSAGES:
        label: teachers.assignment.permission.view_my_messages.label
        group_names: ""
        apply_to_all: false
        apply_to_entities:
            - 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
    VIEW_CM_GENERAL_MESSAGES:
        label: teachers.assignment.permission.view_cm_general.label
        group_names: ""
        apply_to_all: false
        apply_to_entities:
            - 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
