placeholders:
    items:
        teachers_assignment_button:
            template: TeachersAssignmentBundle:Assignment:activityButton.html.twig
            acl: teachers_assignment_create

        teachers_assignment_link:
            template: TeachersAssignmentBundle:Assignment:activityLink.html.twig
            acl: teachers_assignment_create

        teachers_assignment_private_note_button:
            template: TeachersAssignmentBundle:AssignmentPrivateNote:activityButton.html.twig
            acl: teachers_assignment_private_note_create

        teachers_assignment_private_note_link:
            template: TeachersAssignmentBundle:AssignmentPrivateNote:activityLink.html.twig
            acl: teachers_assignment_private_note_create
