processes:
    definitions:
        convert_mailbox_email_to_assignment_message:
            label: 'Convert Mailbox Email to Assignment Message'
            enabled: true
            entity: Oro\Bundle\EmailBundle\Entity\EmailBody
            order: 150
            actions_configuration:
                -   '@find_entity':
                        class: Oro\Bundle\EmailBundle\Entity\Email
                        attribute: $.email
                        where:
                            emailBody: $id
                -   '@find_mailboxes':
                        attribute: $.mailboxes
                        process_type: 'assignment_message'
                        email: $.email
                -   '@tree':
                        conditions:
                            '@not_empty': [ $.mailboxes ]
                        actions:
                            -   '@strip_html_tags':
                                    attribute: $.messageContent
                                    html: $bodyContent
                            -   '@parse_assignment_identifier':
                                    attribute: $.assignmentIdentifier
                                    value: $.email.subject
                            -   '@find_entity':
                                    parameters:
                                        class: Teachers\Bundle\AssignmentBundle\Entity\Assignment
                                        attribute: $.assignment
                                        where:
                                            id: $.assignmentIdentifier
                -   '@tree':
                        conditions:
                            '@and':
                                -   '@gt': [ $.email.sentAt, $.mailbox.updatedAt ]
                                -   '@instanceof': [ $.assignment, Teachers\Bundle\AssignmentBundle\Entity\Assignment ]
                        actions:
                            -   '@create_entity':
                                    class: Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage
                                    attribute: $.messageEntity
                                    flush: true
                                    data:
                                        owner: $.mailbox.processSettings.owner
                                        message: $.messageContent
