teachers_assignment:
    resource: "@TeachersAssignmentBundle/Controller/AssignmentController.php"
    type: annotation
    prefix: /assignment

teachers_assignment_teacher:
    resource: "@TeachersAssignmentBundle/Controller/AssignmentTeacherController.php"
    type: annotation
    prefix: /assignment_teacher

teachers_assignment_my_courses:
    resource: "@TeachersAssignmentBundle/Controller/MyCoursesController.php"
    type: annotation
    prefix: /my_courses

teachers_assignment_private_note:
    resource: "@TeachersAssignmentBundle/Controller/AssignmentPrivateNoteController.php"
    type: annotation
    prefix: /assignment_private_note

teachers_assignment_message:
    resource: "@TeachersAssignmentBundle/Controller/AssignmentMessageController.php"
    type: annotation
    prefix: /assignment_message

teachers_assignment_message_thread:
    resource: "@TeachersAssignmentBundle/Controller/AssignmentMessageThreadController.php"
    type: annotation
    prefix: /assignment_message_thread

teachers_assignment_message_my:
    resource: "@TeachersAssignmentBundle/Controller/MyMessagesController.php"
    type: annotation
    prefix: /assignment_message_my

teachers_assignment_message_cm_my:
    resource: "@TeachersAssignmentBundle/Controller/CmMyMessagesController.php"
    type: annotation
    prefix: /assignment_message_cm_my

teachers_assignment_api:
    resource: "@TeachersAssignmentBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix: api/rest/{version}
    requirements:
        version: latest|v1
        _format: json
    defaults:
        version: latest
