services:
    teachers.workflow.action.send_assignment_message_email_template:
        parent: oro_email.workflow.action.send_email_template
        class: Teachers\Bundle\AssignmentBundle\Workflow\Action\SendMessageApprovedEmail
        arguments:
            - '@teachers_users.helper.role'
        calls:
            - [ setLogger, [ '@logger' ] ]
            - [ setSender, [ '@oro_email.sender.aggregated_email_templates' ] ]
        tags:
            - { name: oro_action.action, alias: send_assignment_message_email_template }
