services:
    teachers_assignment.provider.mailbox_process.assignment_message:
        class: Teachers\Bundle\AssignmentBundle\Provider\AssignmentMessageMailboxProcessProvider
        tags:
            - { name: oro_email.mailbox_process, type: assignment_message }
    teachers_assignment.embedded_form:
        class: Teachers\Bundle\AssignmentBundle\Form\Type\AssignmentType
        public: true
        tags:
            - { name: oro_embedded_form, type: Teachers\Bundle\AssignmentBundle\Form\Type\AssignmentType, label: teachers.assignment.entity_label }
            - { name: form.type, alias: teachers_assignment_request }
    teachers_assignment_private_note.embedded_form:
        class: Teachers\Bundle\AssignmentBundle\Form\Type\AssignmentPrivateNoteType
        public: true
        tags:
            - { name: oro_embedded_form, type: Teachers\Bundle\AssignmentBundle\Form\Type\AssignmentPrivateNoteType, label: teachers.assignment.private_note.entity_label }
            - { name: form.type, alias: teachers_assignment_private_note_request }
    teachers_assignment.activity_list.provider:
        class: Teachers\Bundle\AssignmentBundle\Provider\AssignmentActivityListProvider
        arguments:
            - "@oro_entity.doctrine_helper"
            - "@oro_security.owner.entity_owner_accessor.link"
            - "@oro_activity.association_helper"
            - "@oro_comment.association_helper"
        tags:
            - { name: oro_activity_list.provider, class: Teachers\Bundle\AssignmentBundle\Entity\Assignment, priority: 20 }
    teachers_assignment_private_note.activity_list.provider:
        class: Teachers\Bundle\AssignmentBundle\Provider\AssignmentPrivateNoteActivityListProvider
        arguments:
            - "@oro_entity.doctrine_helper"
            - "@oro_security.owner.entity_owner_accessor.link"
            - "@oro_activity.association_helper"
            - "@oro_comment.association_helper"
        tags:
            - { name: oro_activity_list.provider, class: Teachers\Bundle\AssignmentBundle\Entity\AssignmentPrivateNote, priority: 20 }
    teachers_assignment_message.activity_list.provider:
        class: Teachers\Bundle\AssignmentBundle\Provider\AssignmentMessageActivityListProvider
        arguments:
            - "@oro_entity.doctrine_helper"
            - "@oro_security.owner.entity_owner_accessor.link"
            - "@oro_activity.association_helper"
            - "@oro_comment.association_helper"
            - '@translator'
            - '@teachers_users.helper.role'
        tags:
            - { name: oro_activity_list.provider, class: Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage, priority: 20 }
    teachers_assignment.assignment.form:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - "teachers_assignment_request"
            - Teachers\Bundle\AssignmentBundle\Form\Type\AssignmentType
            - null
    teachers_assignment.assignment_private_note.form:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - "teachers_assignment_private_note_request"
            - Teachers\Bundle\AssignmentBundle\Form\Type\AssignmentPrivateNoteType
            - null
    teachers_assignment.assignment.form.handler:
        class: Teachers\Bundle\AssignmentBundle\Form\Handler\AssignmentHandler
        public: true
        arguments:
            - "@teachers_assignment.assignment.form"
            - "@request_stack"
            - "@doctrine"
    teachers_assignment.assignment_private_note.form.handler:
        class: Teachers\Bundle\AssignmentBundle\Form\Handler\AssignmentPrivateNoteHandler
        public: true
        arguments:
            - "@teachers_assignment.assignment_private_note.form"
            - "@request_stack"
            - "@doctrine"
    teachers_assignment.assignment.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Teachers\Bundle\AssignmentBundle\Entity\Assignment'
            - "@doctrine.orm.entity_manager"
    teachers_assignment.placeholder.filter:
        class: Teachers\Bundle\AssignmentBundle\Placeholder\PlaceholderFilter
        arguments:
            - '@oro_workflow.manager'
        public: true
    teachers_assignment.message.datagrid_view_list:
        class: Teachers\Bundle\AssignmentBundle\Datagrid\MessagesViewList
        public: true
        arguments:
            - '@translator'
    teachers_assignment.my_messages.datagrid_view_list:
        class: Teachers\Bundle\AssignmentBundle\Datagrid\MyMessagesViewList
        public: true
        arguments:
            - '@translator'
    teachers_assignment.my_messages.cm_general_messages_view_list:
        class: Teachers\Bundle\AssignmentBundle\Datagrid\CmGeneralMessagesViewList
        public: true
        arguments:
            - '@translator'
    teachers_assignment.assignments.datagrid_view_list:
        class: Teachers\Bundle\AssignmentBundle\Datagrid\AssignmentsViewList
        public: true
        arguments:
            - '@translator'
            - '@teachers_users.helper.role'
    teachers_assignment.event_listener.orm.assignment_postupdate:
        class: Teachers\Bundle\AssignmentBundle\EventListener\ORM\AssignmentPostupdate
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine.event_listener, event: postUpdate, connection: default, entity: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment' }
    teachers_assignment.event_listener.orm.assignment_amount_due_today_post_persist:
        class: Teachers\Bundle\AssignmentBundle\EventListener\ORM\AssignmentAmountDueTodayPostPersist
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_workflow.manager'
            - '@oro_activity.manager'
        tags:
            - { name: doctrine.event_listener, priority: 900, event: postPersist, connection: default, entity: 'Teachers\Bundle\AssignmentBundle\Entity\Assignment' }
            - { name: doctrine.event_listener, event: postFlush }
    teachers_assignment.event_listener.orm.assignment_send_emails_post_persist:
        class: Teachers\Bundle\AssignmentBundle\EventListener\ORM\AssignmentSendEmailsPostPersist
        arguments:
            - '@oro_email.manager.template_email'
            - '@oro_config.manager'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    teachers_assignment.grid.listener:
        class: Teachers\Bundle\AssignmentBundle\EventListener\AssignmentGridListener
        arguments:
            - '@teachers_users.helper.role'
        tags:
            - name: kernel.event_listener
              event: oro_datagrid.datagrid.build.before.teachers-assignments-grid
              method: onBuildBefore
    teachers_assignment.my_messages.hide_denial_reason_column:
        class: Teachers\Bundle\AssignmentBundle\EventListener\HideDenialReasonColumnForStudent
        arguments:
            - '@teachers_users.helper.role'
        tags:
            - name: kernel.event_listener
              event: oro_datagrid.datagrid.build.before.teachers-assignment-my-messages-grid
              method: onBuildBefore
    teachers_assignment.thread_messages.hide_denial_reason_column:
        class: Teachers\Bundle\AssignmentBundle\EventListener\HideDenialReasonColumnForStudent
        arguments:
            - '@teachers_users.helper.role'
        tags:
            - name: kernel.event_listener
              event: oro_datagrid.datagrid.build.before.teachers-thread-messages-grid
              method: onBuildBefore
    teachers_assignment.my_messages.hide_appove_actions_for_students_tutors:
        class: Teachers\Bundle\AssignmentBundle\EventListener\HideAppoveActionsForStudentsTutors
        arguments:
            - '@teachers_users.helper.role'
        tags:
            - name: kernel.event_listener
              event: oro_datagrid.datagrid.build.before.teachers-assignment-messages-grid
              method: onBuildBefore
    teachers_assignment.topic.new_message:
        class: Oro\Bundle\SyncBundle\Topic\BroadcastTopic
        arguments:
            - 'teachers_assignment.new_message'
        tags:
            - { name: gos_web_socket.topic }
    teachers_assignment.event_listener.orm.notify_user_new_message:
        class: Teachers\Bundle\AssignmentBundle\EventListener\ORM\NotifyUserNewMessage
        arguments:
            - '@teachers_users.helper.role'
            - '@oro_sync.websocket_client.basic'
        tags:
            - {
                name: doctrine.event_listener,
                priority: 900,
                event: postPersist,
                connection: default,
                entity: 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
            }
            - {
                name: doctrine.event_listener,
                event: postUpdate,
                entity: 'Teachers\Bundle\AssignmentBundle\Entity\AssignmentMessage'
            }
    teachers_assignment.helper.messages:
        class: Teachers\Bundle\AssignmentBundle\Helper\Messages
        public: true
        arguments:
            - "@teachers_users.helper.role"
            - '@oro_workflow.manager'
            - '@doctrine.orm.entity_manager'
