datagrids:
    teachers-groups-grid:
        extended_entity_name: 'Teachers\Bundle\UsersBundle\Entity\TeacherGroup'
        acl_resource: teachers_group_view
        source:
            type: orm
            query:
                select:
                    - teachergroup.id
                    - teachergroup.title
                from:
                    - { table: 'Teachers\Bundle\UsersBundle\Entity\TeacherGroup', alias: teachergroup }
        columns:
            title:
                label: teachers.users.teacher_group.title.label
        sorters:
            columns:
                title:
                    data_name: teachergroup.title
            default:
                title: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: teachergroup.title
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_group_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_group_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_group_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_group_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_group_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_group_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.users.teacher_group.entity_plural_label
            entity_pagination: true

    users-by-role-select-grid:
        extends: users-select-grid
        source:
            query:
                join:
                    left:
                        - { join: u.roles, alias: r }
                where:
                    and:
                        - r.id = :role_id
            bind_parameters:
                -   name: role_id
                    default: null
    users-grid:
        views_list: "@teachers_users.user.datagrid_view_list"
        source:
            query:
                select:
                    - r.role as roleName
                    - r.label as roleLabel
                join:
                    left:
                        - { join: u.roles, alias: r }
        columns:
            roleLabel:
                label: teachers.users.users.roleLabel.label
        filters:
            columns:
                roleLabel:
                    type: choice
                    data_name: r.role
                    label: teachers.users.users.roleLabel.label
                    frontend_type: select
                    options:
                        field_options:
                            choices:
                                teachers.users.users.roleLabel.courseManager.label: ROLE_COURSE_MANAGER
                                teachers.users.users.roleLabel.student.label: ROLE_STUDENT
                                teachers.users.users.roleLabel.teacher.label: ROLE_TEACHER
