datagrids:
    teachers-groups-grid:
        extended_entity_name: 'Teachers\Bundle\UsersBundle\Entity\TeacherGroup'
        acl_resource: teachers_group_view
        source:
            type: orm
            query:
                select:
                    - teachergroup.id
                    - teachergroup.title
                from:
                    - { table: 'Teachers\Bundle\UsersBundle\Entity\TeacherGroup', alias: teachergroup }
        columns:
            title:
                label: teachers.users.teacher_group.title.label
        sorters:
            columns:
                title:
                    data_name: teachergroup.title
            default:
                title: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: teachergroup.title
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_group_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_group_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_group_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_group_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_group_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_group_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.users.teacher_group.entity_plural_label
            entity_pagination: true

    teachers-role-user-select-grid:
        extends: users-select-grid
        source:
            query:
                join:
                    left:
                        - { join: u.roles, alias: r }

    course-manager-select-grid:
        extends: teachers-role-user-select-grid
        source:
            query:
                where:
                    and:
                        - r.id = @teachers_users.helper.role->getCourseManagerRoleId

    teacher-select-grid:
        extends: teachers-role-user-select-grid
        source:
            query:
                where:
                    and:
                        - r.id = @teachers_users.helper.role->getTeacherRoleId

    student-select-grid:
        extends: teachers-role-user-select-grid
        source:
            query:
                where:
                    and:
                        - r.id = @teachers_users.helper.role->getStudentRoleId
