navigation:
    menu_config:
        items:
            teachers_group:
                label: 'teachers.users.teacher_group.entity_plural_label'
                route: 'teachers_group_index'
                position: 14
                extras:
                    routes: [ 'teachers_group_*' ]
                    icon: fa-users
                display: true
        tree:
            application_menu:
                children:
                    teachers_group: ~
    titles:
        teachers_group_index: ~
        teachers_group_view: '%teacher_group.title%'
        teachers_group_create: 'Create teacher group'
        teachers_group_update: '%teacher_group.title% - Edit'
