navigation:
    menu_config:
        items:
            billing_tab:
                label: 'teachers.invoice.billing.menu.billing_tab.label'
                uri: '#'
                position: 31
                extras:
                    icon: fa-credit-card
            teachers_invoice_invoice:
                label: 'teachers.invoice.entity_plural_label'
                route: 'teachers_invoice_index'
                extras:
                    routes: [ 'teachers_invoice_*' ]
                display: true
            teachers_invoice_payment:
                label: 'teachers.payment.entity_plural_label'
                route: 'teachers_payment_index'
                extras:
                    routes: [ 'teachers_payment_*' ]
                display: true
            teachers_invoice_report_tab:
                label: 'teachers.invoice.menu.invoices_report_tab.label'
                uri: '#'
                position: 30
                extras:
                    skipBreadcrumbs: true
            teachers_invoice_report:
                label: 'teachers.invoice.menu.invoices_report_base.label'
                route: 'oro_reportcrm_index'
                route_parameters:
                    reportGroupName: 'invoices'
                    reportName: 'base'
                extras:
                    description: 'teachers.invoice.menu.invoices_report_base.description'
                    skipBreadcrumbs: true
        tree:
            application_menu:
                children:
                    billing_tab:
                        children:
                            teachers_invoice_invoice: ~
                            teachers_invoice_payment: ~
                    reports_tab:
                        children:
                            static_reports_tab:
                                children:
                                    teachers_invoice_report_tab:
                                        children:
                                            teachers_invoice_report: ~
    titles:
        teachers_invoice_index: ~
        teachers_invoice_view: '%invoice.id%'
        teachers_invoice_create: 'Create Invoice'
        teachers_invoice_update: '%invoice.id% - Edit'

        teachers_payment_index: ~
        teachers_payment_view: '%payment.id%'
        teachers_payment_create: 'Create Payment'
        teachers_payment_update: '%payment.id% - Edit'
