placeholders:
    items:
        teachers_invoice_button:
            template: TeachersInvoiceBundle:Invoice:activityButton.html.twig
            applicable: '@teachers_invoice.placeholder.filter->isAssignmentUpForInvoice($entity$)'
            acl: teachers_invoice_create
        teachers_invoice_link:
            template: TeachersInvoiceBundle:Invoice:activityLink.html.twig
            applicable: '@teachers_invoice.placeholder.filter->isAssignmentUpForInvoice($entity$)'
            acl: teachers_invoice_create
