workflows:
    invoice_flow:
        entity_restrictions:
            invoice_status_creation:
                attribute: invoice
                field: status
                mode: disallow
                values:
                    - 'paid'
                    - 'partially_paid'
            invoice_status_unpaid:
                attribute: invoice
                field: status
                step: unpaid
            invoice_status_paid:
                attribute: invoice
                field: status
                step: paid
            invoice_status_partially_paid:
                attribute: invoice
                field: status
                step: partially_paid
