workflows:
    invoice_flow:
        steps:
            unpaid:
                order: 10
                allowed_transitions:
                    - pay
            partially_paid:
                order: 15
                allowed_transitions:
                    - pay
            paid:
                order: 20
                allowed_transitions:
                    - reopen
