workflows:
    invoice_flow:
        transitions:
            reopen:
                step_to: unpaid
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-pencil-square-o'
                transition_definition: reopen_definition
