workflows:
    invoice_flow:
        transition_definitions:
            __start___definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: invoice_status
                            identifier: unpaid
                            attribute: $invoice.status
