workflows:
    invoice_flow:
        transitions:
            make_paid:
                step_to: paid
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-check'
                transition_definition: make_paid_definition
            reopen:
                step_to: unpaid
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-pencil-square-o'
                transition_definition: reopen_definition
