workflows:
    invoice_flow:
        transitions:
            pay:
                step_to: partially_paid
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-credit-card'
                transition_definition: pay_definition
                form_options:
                    attribute_fields:
                        amountPaid:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroMoneyType
                            options:
                                required: true
                                constraints:
                                    -   NotBlank: ~
            reopen:
                step_to: unpaid
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-pencil-square-o'
                transition_definition: reopen_definition
