layout:
    actions:
        -   '@setBlockTheme':
                themes: 'TeachersApplicationBundle:layouts:embedded_default/oro_embedded_form_submit/form.html.twig'
        -   '@setOption':
                id: embedded_form
                optionName: preferred_fields
                optionValue: [ subject, description, studentLoginInfo, price, status ]
        -   '@add':
                id: name_group
                parentId: embedded_form
                blockType: fieldset
        -   '@move':
                id: embedded_form_firstName
                parentId: name_group
        -   '@move':
                id: embedded_form_lastName
                parentId: name_group

    conditions: 'context["embedded_form_type"] == "Teachers\\Bundle\\ApplicationBundle\\Form\\Type\\ApplicationType"'
