workflows:
    application_flow:
        transitions:
            start_working:
                step_to: working
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-play'
                transition_definition: start_working_definition
            stop_working:
                step_to: new
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-stop'
                transition_definition: stop_working_definition
            complete:
                step_to: complete
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-check'
                transition_definition: complete_definition
            reopen:
                step_to: new
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-pencil-square-o'
                transition_definition: reopen_definition
