workflows:
    assignment_message_flow:
        steps:
            pending:
                order: 10
                allowed_transitions:
                    - approve
                    - unapprove
            approved:
                order: 20
                allowed_transitions:
                    - unapprove
            not_approved:
                order: 30
                allowed_transitions:
                    - approve
