workflows:
    assignment_message_flow:
        transition_definitions:
            __start___definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_msg_status
                            identifier: pending
                            attribute: $assignment_message.status
            approve_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_msg_status
                            identifier: approved
                            attribute: $assignment_message.status
                    -   '@send_assignment_message_email_template':
                            from: 'email@address.com'
                            to: 'will_be_redefined'
                            template: 'teachers_assignment_message_approved'
                            entity: $assignment_message
            unapprove_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_msg_status
                            identifier: not_approved
                            attribute: $assignment_message.status
                    -   '@send_email_template':
                            from: 'email@address.com'
                            to: $assignment_message.owner.email
                            template: 'teachers_assignment_message_rejected'
                            entity: $assignment_message
