workflows:
    assignment_message_flow:
        transitions:
            approve:
                step_to: approved
                frontend_options:
                    icon: 'fa-thumbs-up'
                transition_definition: approve_definition
            unapprove:
                step_to: not_approved
                frontend_options:
                    icon: 'fa-thumbs-down'
                    class: 'hide'
                transition_definition: unapprove_definition
            refresh:
                step_to: pending
                frontend_options:
                    icon: 'fa-refresh'
                transition_definition: refresh_definition
