services:
    teachers_application.embedded_form:
        class: Teachers\Bundle\ApplicationBundle\Form\Type\ApplicationType
        public: true
        tags:
            - { name: oro_embedded_form, type: Teachers\Bundle\ApplicationBundle\Form\Type\ApplicationType, label: teachers.application.application.entity_label }
            - { name: form.type, alias: teachers_application_request }

    teachers_application.application.form:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - "teachers_application_request"
            - Teachers\Bundle\ApplicationBundle\Form\Type\ApplicationType
            - null

    teachers_application.application.form.handler:
        class: Teachers\Bundle\ApplicationBundle\Form\Handler\ApplicationHandler
        public: true
        arguments:
            - "@teachers_application.application.form"
            - "@request_stack"
            - "@doctrine"

    teachers_application.application.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Teachers\Bundle\ApplicationBundle\Entity\Application'
            - "@doctrine.orm.entity_manager"
