datagrids:
  satisfactions-grid:
    extended_entity_name: 'Teachers\Bundle\SatisfactionBundle\Entity\Satisfaction'
    acl_resource: teachers_satisfaction_view
    source:
      type: orm
      query:
        select:
          - satisfaction.id
          - satisfaction.subject
          - satisfaction.description
          - satisfaction.dueDate
          - CONCAT_WS(' ', own.firstName, own.lastName) as ownerName
          - own.id as owner
          - satisfaction.createdAt
          - satisfaction.updatedAt
        from:
          - { table: 'Teachers\Bundle\SatisfactionBundle\Entity\Satisfaction', alias: satisfaction }
        join:
          inner:
            - { join: satisfaction.owner, alias: own }
    inline_editing:
      enable: true
    columns:
      subject:
        label: teachers.satisfaction.subject.label
      ownerName:
        label: teachers.satisfaction.owner.label
        inline_editing:
          enable: true
          editor:
            view: oroform/js/app/views/editor/related-id-relation-editor-view
            view_options:
              value_field_name: owner
          autocomplete_api_accessor:
            class: orouser/js/tools/acl-users-search-api-accessor
            permission_check_entity_name: Teachers_Bundle_SatisfactionBundle_Entity_Satisfaction
      createdAt:
        label: oro.ui.created_at
        frontend_type: datetime
      updatedAt:
        label: oro.ui.updated_at
        frontend_type: datetime
      tags: [ ]
      contexts: [ ]

    sorters:
      columns:
        subject:
          data_name: satisfaction.subject
        ownerName:
          data_name: ownerName
        createdAt:
          data_name: satisfaction.createdAt
        updatedAt:
          data_name: satisfaction.updatedAt
      default:
        dueDate: ASC
    filters:
      columns:
        subject:
          type: string
          data_name: satisfaction.subject
        owner:
          type: choice-tree
          label: teachers.satisfaction.owner.label
          data_name: satisfaction.owner
          autocomplete_alias: assigned_to_organization_users
          renderedPropertyName: 'fullName'
          className: 'Oro\Bundle\UserBundle\Entity\User'
        businessUnitId:
          label: oro.business_unit.label
          type: choice-business-unit
          data_name: satisfaction.owner
          className: 'Oro\Bundle\OrganizationBundle\Entity\BusinessUnit'
        createdAt:
          type: datetime
          data_name: satisfaction.createdAt
        updatedAt:
          type: datetime
          data_name: satisfaction.updatedAt
    properties:
      id: ~
      owner: ~
      view_link:
        type: url
        route: teachers_satisfaction_view
        params: [ id ]
      update_link:
        type: url
        route: teachers_satisfaction_update
        params: [ id ]
    actions:
      view:
        type: navigate
        acl_resource: teachers_satisfaction_view
        label: oro.grid.action.view
        icon: eye
        link: view_link
        rowAction: true
      update:
        type: navigate
        acl_resource: teachers_satisfaction_update
        label: oro.grid.action.update
        icon: edit
        link: update_link
    options:
      entity_pagination: true
      contexts:
        enabled: true

  widget-base-satisfactions-grid:
    acl_resource: teachers_satisfaction_view
    source:
      type: orm
      query:
        select:
          - satisfaction.id
          - satisfaction.subject
          - CONCAT_WS(' ', owner.firstName, owner.lastName) as ownerName
          - owner.id as ownerId
        from:
          - { table: 'Teachers\Bundle\SatisfactionBundle\Entity\Satisfaction', alias: satisfaction }
        join:
          left:
            - { join: satisfaction.owner, alias: owner }
    columns:
      subject:
        label: teachers.satisfaction.subject.label
        type: twig
        template: TeachersSatisfactionBundle:Satisfaction:Datagrid/Property/subject.html.twig
        frontend_type: html
      ownerName:
        type: twig
        label: teachers.satisfaction.owner.label
        frontend_type: html
        template: TeachersSatisfactionBundle:Satisfaction:Datagrid/Property/owner.html.twig
    sorters:
      columns:
        subject:
          data_name: satisfaction.subject
        ownerName:
          data_name: ownerName
      default:
        dueDate: ASC
    filters:
      columns:
        subject:
          type: string
          data_name: satisfaction.subject
        ownerName:
          type: string
          data_name: ownerName
    properties:
      id: ~

  activity-satisfactions-grid:
    extends: widget-base-satisfactions-grid

  user-satisfactions-grid:
    extends: satisfactions-grid
    options:
      entity_pagination: false

  satisfaction-for-context-grid:
    extended_entity_name: 'Teachers\Bundle\SatisfactionBundle\Entity\Satisfaction'
    acl_resource: teachers_satisfaction_view
    options:
      entityHint: teachers.satisfaction.entity_plural_label
      entity_pagination: true
      toolbarOptions:
        pageSize:
          default_per_page: 10
      routerEnabled: false

    source:
      type: orm
      query:
        select:
          - satisfaction.id
          - satisfaction.subject
          - satisfaction.description
          - CONCAT_WS(' ', own.firstName, own.lastName) as ownerName
          - own.id as owner
        from:
          - { table: 'Teachers\Bundle\SatisfactionBundle\Entity\Satisfaction', alias: satisfaction }
        join:
          left:
            - { join: satisfaction.owner, alias: own }
      hints:
        - HINT_TRANSLATABLE
    columns:
      id:
        label: teachers.satisfaction.id.label
      subject:
        label: teachers.satisfaction.subject.label
      ownerName:
        label: teachers.satisfaction.owner.label
    sorters:
      columns:
        subject:
          data_name: satisfaction.subject
        ownerName:
          data_name: ownerName
      default:
        dueDate: ASC
    filters:
      columns:
        subject:
          type: string
          data_name: satisfaction.subject
        owner:
          type: choice-tree
          label: teachers.satisfaction.owner.label
          data_name: satisfaction.owner
          options:
            lazy: "@oro_user.provider.filter.user_choice_tree->shouldBeLazy"
            data: "@?oro_user.provider.filter.user_choice_tree->getList"
