api:
    entities:
        Teachers\Bundle\ApplicationBundle\Entity\Application:
            fields:
                reCaptchaToken:
                    exclude: true
                    data_type: string
            actions:
                create:
                    fields:
                        reCaptchaToken:
                            exclude: false
