datagrids:
    teachers-applications-grid:
        extended_entity_name: 'Teachers\Bundle\ApplicationBundle\Entity\Application'
        acl_resource: teachers_application_view
        source:
            type: orm
            query:
                select:
                    - application.id
                    - application.firstName
                    - application.lastName
                    - application.email
                    - application.phone
                    - application.courseName
                    - application.coursePrefixes
                    - application.amountDueToday
                    - application.price
                    - application.workToday
                    - application.dueDate
                    - application.courseUrl
                    - application.userLogin
                    - applicationterm.name as termName
                    - applicationterm.id as termId
                    - application.createdAt
                from:
                    - { table: 'Teachers\Bundle\ApplicationBundle\Entity\Application', alias: application }
                join:
                    left:
                        - { join: application.term, alias: applicationterm }
        columns:
            firstName:
                label: teachers.application.first_name.label
            lastName:
                label: teachers.application.last_name.label
            email:
                label: teachers.application.email.label
            phone:
                label: teachers.application.phone.label
            courseName:
                label: teachers.application.course_name.label
            coursePrefixes:
                label: teachers.application.course_prefixes.label
            amountDueToday:
                label: teachers.application.amountDueToday.label
                type: twig
                frontend_type: html
                template: TeachersApplicationBundle:Datagrid:price.html.twig
            price:
                label: teachers.application.price.label
                type: twig
                frontend_type: html
                template: TeachersApplicationBundle:Datagrid:price.html.twig
            workToday:
                label: teachers.application.work_today.label
                frontend_type: select
                choices:
                    teachers.application.work_today.true.label: 1
                    teachers.application.work_today.false.label: 0
            dueDate:
                frontend_type: datetime
                label: teachers.application.due_date.label
            courseUrl:
                label: teachers.application.course_url.label
            userLogin:
                label: teachers.application.user_login.label
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
            termName:
                label: teachers.application.term.label
        sorters:
            columns:
                firstName:
                    data_name: application.firstName
                lastName:
                    data_name: application.lastName
                email:
                    data_name: application.email
                phone:
                    data_name: application.phone
                courseName:
                    data_name: application.courseName
                coursePrefixes:
                    data_name: application.coursePrefixe
                amountDueToday:
                    data_name: application.amountDueToday
                price:
                    data_name: application.price
                dueDate:
                    data_name: application.dueDate
                courseUrl:
                    data_name: application.courseUrl
                userLogin:
                    data_name: application.userLogin
                createdAt:
                    data_name: application.createdAt
                termName:
                    data_name: termName
            default:
                createdAt: DESC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: application.firstName
                lastName:
                    type: string
                    data_name: application.lastName
                email:
                    type: string
                    data_name: application.email
                phone:
                    type: string
                    data_name: application.phone
                courseName:
                    type: string
                    data_name: application.courseName
                coursePrefixe:
                    type: string
                    data_name: application.coursePrefixe
                amountDueToday:
                    type: string
                    data_name: application.amountDueToday
                price:
                    type: string
                    data_name: application.price
                workToday:
                    data_name: c.enabled
                    type: choice
                    options:
                        field_options:
                            choices:
                                teachers.application.work_today.false.label: 0
                                teachers.application.work_today.true.label: 1
                dueDate:
                    type: string
                    data_name: application.dueDate
                courseUrl:
                    type: string
                    data_name: application.courseUrl
                userLogin:
                    type: string
                    data_name: application.userLogin
                createdAt:
                    type: datetime
                    data_name: application.createdAt
                termName:
                    type: enum
                    enum_code: application_term
                    data_name: termId
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_application_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_application_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_application_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_application_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_application_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_application_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.application.entity_plural_label
            entity_pagination: true
