navigation:
    menu_config:
        items:
            teachers_application_tab:
                label: 'teachers.application.course_managers_queue'
                route: 'teachers_application_index'
                position: 11
                extras:
                    routes: [ 'teachers_application_*' ]
                    icon: fa-folder
                display: true
        tree:
            application_menu:
                children:
                    teachers_application_tab: ~
    titles:
        teachers_application_index: ~
        teachers_application_view: '%application.courseName%'
        teachers_application_create: 'Create application'
        teachers_application_update: '%application.courseName% - Edit'
