search:
    Teachers\Bundle\ApplicationBundle\Entity\Application:
        alias: teachers_application
        title_fields: [ courseName ]
        route:
            name: teachers_application_view
            parameters:
                id: id
        search_template: TeachersApplicationBundle:Search:result.html.twig
        fields:
            -   name: courseName
                target_type: text
                target_fields: [ courseName ]
            -   name: description
                target_type: text
                target_fields: [ description ]
