services:
    teachers_users.embedded_form:
        class: Teachers\Bundle\UsersBundle\Form\Type\TeacherGroupType
        public: true
        tags:
            - { name: oro_embedded_form, type: Teachers\Bundle\UsersBundle\Form\Type\TeacherGroupType, label: teachers.users.teacher_group.entity_label }
            - { name: form.type, alias: teachers_group_request }
    teachers_users.teacher_group.form:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - "teachers_group_request"
            - Teachers\Bundle\UsersBundle\Form\Type\TeacherGroupType
            - null
