services:
    teachers_users.helper.role:
        class: Teachers\Bundle\UsersBundle\Helper\Role
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
    teachers_users.teacher_group.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Teachers\Bundle\UsersBundle\Entity\TeacherGroup'
            - "@doctrine.orm.entity_manager"


