workflows:
    assignment_flow:
        attributes:
            teacher:
                type: entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            assignment_value:
                type: float
