workflows:
    assignment_flow:
        entity_restrictions:
            assignment_status_creation:
                attribute: assignment
                field: status
                mode: disallow
                values:
                    - 'assigned'
                    - 'complete'
            assignment_status_new:
                attribute: assignment
                field: status
                step: new
            assignment_status_up_for_bid:
                attribute: assignment
                field: status
                step: up_for_bid
            assignment_status_paused_due_nonpayment:
                attribute: assignment
                field: status
                step: paused_due_nonpayment
            assignment_status_assigned:
                attribute: assignment
                field: status
                step: assigned
            assignment_status_complete:
                attribute: assignment
                field: status
                step: complete
