workflows:
    assignment_flow:
        steps:
            new:
                order: 10
                allowed_transitions:
                    - start_accepting_bids
                    - assign
                    - complete
            up_for_bid:
                order: 20
                allowed_transitions:
                    - stop_accepting_bids
                    - assign
                    - complete
            assigned:
                order: 30
                allowed_transitions:
                    - complete
            complete:
                order: 40
                allowed_transitions:
                    - reopen
