workflows:
    assignment_flow:
        transitions:
            start_accepting_bids:
                step_to: up_for_bid
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-play'
                transition_definition: start_accepting_bids_definition
            stop_accepting_bids:
                step_to: new
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-stop'
                transition_definition: stop_accepting_bids_definition
            complete:
                step_to: complete
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-check'
                transition_definition: complete_definition
            continue:
                step_to: assigned
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-play'
                transition_definition: continue_definition
            pause_due_nonpayment:
                step_to: paused_due_nonpayment
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-pause'
                transition_definition: pause_due_nonpayment_definition
            reopen:
                step_to: new
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-pencil-square-o'
                transition_definition: reopen_definition
            assign:
                step_to: assigned
                is_start: true
                is_unavailable_hidden: true
                acl_resource: teachers_assignment_update
                frontend_options:
                    icon: 'fa-address-card'
                transition_definition: assign_definition
                form_options:
                    attribute_fields:
                        teacher:
                            form_type: Teachers\Bundle\UsersBundle\Form\Type\TeacherSelectType
                            options:
                                required: true
