workflows:
    assignment_flow:
        transition_definitions:
            __start___definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: new
                            attribute: $assignment.status
            start_accepting_bids_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: up_for_bid
                            attribute: $assignment.status
            stop_accepting_bids_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: new
                            attribute: $assignment.status
            assign_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: assigned
                            attribute: $assignment.status
                    -   '@call_method': # add Account
                            object: $assignment
                            method: setTeacher
                            method_parameters: [ $teacher ]
            complete_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: complete
                            attribute: $assignment.status
            reopen_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: new
                            attribute: $assignment.status
