workflows:
    assignment_flow:
        transition_definitions:
            __start___definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: new
                            attribute: $assignment.status
            start_accepting_bids_definition:
                conditions:
                    '@or':
                        parameters:
                            -   '@equal': [ $assignment.amountDueToday, 0 ]
                            -   '@equal': [ $assignment.invoiceDueTodayPaid, 1 ]
                        message: 'Amount due today must be 0 or the invoice with this amount must be paid'
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: up_for_bid
                            attribute: $assignment.status
            stop_accepting_bids_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: new
                            attribute: $assignment.status
            assign_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: assigned
                            attribute: $assignment.status
                    -   '@call_method': # add Account
                            object: $assignment
                            method: setTeacher
                            method_parameters: [ $teacher ]
            pause_due_nonpayment_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: paused_due_nonpayment
                            attribute: $assignment.status
            continue_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: assigned
                            attribute: $assignment.status
            complete_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: complete
                            attribute: $assignment.status
            reopen_definition:
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: new
                            attribute: $assignment.status
