workflows:
    application_flow:
        transition_definitions:
            __start___definition:
              actions:
                  - '@request_enum_entity':
                      enum_code: application_status
                      identifier: new
                      attribute: $application.status
            start_working_definition:
              actions:
                  - '@request_enum_entity':
                      enum_code: application_status
                      identifier: working
                      attribute: $application.status
            stop_working_definition:
              actions:
                  - '@request_enum_entity':
                      enum_code: application_status
                      identifier: new
                      attribute: $application.status
            complete_definition:
              actions:
                  - '@request_enum_entity':
                      enum_code: application_status
                      identifier: complete
                      attribute: $application.status
            reopen_definition:
              actions:
                  - '@request_enum_entity':
                      enum_code: application_status
                      identifier: new
                      attribute: $application.status

            convert_to_assignment_definition:
                conditions:
                    '@and':
                        -   '@not_empty':
                                parameters: $assignment_subject
                                message: 'Assignment subject must be set'
                        -   '@not_empty':
                                parameters: $assignment_courseManager
                                message: 'Course manager (owner) must be set'
                actions:
                    -   '@request_enum_entity':
                            enum_code: assignment_status
                            identifier: 'new'
                            attribute: $.result.assignment_status
                    -   '@create_entity': # create an assignment
                            class: Teachers\Bundle\AssignmentBundle\Entity\Assignment
                            attribute: $request.assignment
                            data:
                                subject: $assignment_subject
                                courseManager: $assignment_courseManager
                                description: $assignment_description
                                teacher: $assignment_teacher
                                student: $assignment_student
                                status: $.result.assignment_status
                                teacher_groups: $assignment_teacher_groups
