workflows:
    payment_flow:
        steps:
            created:
                order: 10
            partially_refunded:
                order: 20
            fully_refunded:
                order: 30
