datagrids:
    bids-grid:
        extended_entity_name: 'Teachers\Bundle\BidBundle\Entity\Bid'
        acl_resource: teachers_bid_view
        source:
            type: orm
            query:
                select:
                    - bid.id
                    - bid.price
                    - bid.createdAt
                from:
                    - { table: 'Teachers\Bundle\BidBundle\Entity\Bid', alias: bid }
                join:
                    left:
                        - { join: bid.status, alias: bidstatus }
        columns:
            price:
                label: teachers.bid.price.label
                type: twig
                frontend_type: html
                template: TeachersApplicationBundle:Datagrid:price.html.twig
            createdAt:
                frontend_type: datetime
                label: oro.ui.created_at
        sorters:
            columns:
                price:
                    data_name: bid.price
                createdAt:
                    data_name: bid.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                price:
                    type: number-range
                    data_name: bid.price
                createdAt:
                    type: datetime
                    data_name: bid.createdAt
        properties:
            id: ~
            view_link:
                type: url
                route: teachers_bid_view
                params: [ id ]
            update_link:
                type: url
                route: teachers_bid_update
                params: [ id ]
            delete_link:
                type: url
                route: teachers_bid_delete
                params: [ id ]
        actions:
            view:
                acl_resource: teachers_bid_view
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                acl_resource: teachers_bid_edit
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                acl_resource: teachers_bid_delete
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entityHint: teachers.bid.bid.entity_plural_label
            entity_pagination: true

    user-bids-grid:
        extends: bids-grid
        options:
            entity_pagination: false
